name: gantabbya
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  dot_navigation_bar: ^1.0.2
  dio: ^5.6.0
  path_provider: ^2.1.4
  shimmer: ^3.0.0
  intl: ^0.19.0
  responsive_sizer: ^3.3.1
  get_storage: ^2.1.1
  otp_text_field: ^1.1.3
  file_picker: ^8.1.2
  dotted_border: ^2.1.0
  url_launcher: ^6.3.0
  http_parser: ^4.0.2
  cached_network_image: ^3.4.1
  nepali_date_picker: ^6.0.1
  clean_nepali_calendar: ^2.0.1
  carousel_slider: ^5.0.0
  super_bullet_list: ^0.0.3
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
