import 'package:flutter/material.dart';

import 'package:get/get.dart';
import 'package:ikchatbot/ikchatbot.dart';
import '../controllers/chat_controller.dart';

class ChatView extends GetView<ChatController> {
  const ChatView({super.key});

  @override
  Widget build(BuildContext context) {
    final chatBotConfig = IkChatBotConfig(
      backgroundImage: 'assets/images/background.jpg',
      useAsset: true,
      backgroundAssetimage: 'assets/images/background.jpg',
      ratingIconYes: const Icon(Icons.star),
      ratingIconNo: const Icon(Icons.star_border),
      ratingIconColor: Colors.black,
      ratingBackgroundColor: Colors.white,
      ratingButtonText: 'Submit Rating',
      thankyouText: 'Thanks for your rating!',
      ratingText: 'Rate your experience:',
      ratingTitle: 'Thank you for using the chatbot!',
      body: 'This is a test email sent from Flutter and Dart.',
      subject: 'Test Rating',
      recipient: 'recipient@example.com',
      isSecure: true,
      senderName: 'Your Name',
      smtpUsername: 'Your Email',
      smtpPassword: 'your password',
      smtpServer: 'smtp.gmail.com',
      smtpPort: 587,
      sendIcon: const Icon(Icons.send, color: Colors.black),
      userIcon: const Icon(Icons.person, color: Colors.white),
      botIcon: const Icon(Icons.android, color: Colors.white),
      botChatColor: const Color.fromARGB(255, 81, 80, 80),
      delayBot: 100,
      closingTime: 1,
      delayResponse: 1,
      userChatColor: Colors.blue,
      waitingTime: 1,
      keywords: [
        "who are you",
        "what is flutter",
        "insult",
        "apology",
        "lumbini",
        "where is lumbini",
        "langtang",
        "where is langtang",
        "hiking",
        "best trekking in nepal",
        "pokhara",
        "where is pokhara",
        "phewa lake",
        "adventure in pokhara",
        "ilam",
        "where is ilam",
        "chitwan",
        "where is chitwan",
        "chitwan national park",
        "janakpur",
        "where is janakpur",
        "janaki temple",
        "dharan",
        "where is dharan",
        "dhulikhel",
        "where is dhulikhel",
        "kalinchowk",
        "where is kalinchowk",
        "dolpa",
        "where is dolpa",
        "hello",
        "hi",
        "how are you",
        "bye",
        "thanks",
        "thank you",
        "help",
        "support",
        "weather",
        "joke",
        "fact",
        "nepal",
        "food in nepal",
        "festival in nepal",
        "history of nepal",
        "travel to nepal",
        "hotel in nepal",
        "airport in nepal",
        "currency of nepal",
        "emergency number in nepal",
        "doctor in nepal",
        "atm in nepal",
        "bank in nepal",
        "shopping in nepal",
        "bus in nepal",
        "train in nepal",
        "flight in nepal",
        "bike rental in nepal",
        "taxi in nepal",
        "restaurant in nepal",
        "tourist spot in nepal",
        "museum in nepal",
        "temple in nepal",
        "monastery in nepal",
        "Buddha",
        "Hinduism in nepal",
        "meditation in nepal",
        "yoga in nepal",
        "sports in nepal",
        "cricket in nepal",
        "football in nepal",
        "technology in nepal",
        "internet in nepal",
        "fix slow internet",
        "forgot password",
        "contact support",
        "map of nepal",
        "best time to visit nepal",
        "budget travel in nepal",
        "shopping mall in nepal",
        "music in nepal",
        "movie in nepal",
        "festival of lights",
        "new year in nepal",
        "Christmas in nepal",
        "Eid in nepal",
        "Diwali in nepal"
      ],
      responses: [
        "I'm a bot here to assist you.",
        "Flutter is a UI toolkit by Google.",
        "Please use respectful words.",
        "No worries! Let me know how I can help.",
        "Lumbini is the birthplace of Buddha.",
        "It is in Rupandehi District, Nepal.",
        "Langtang Valley is a great trekking destination.",
        "Langtang is in the Himalayas north of Kathmandu.",
        "Hiking is a great way to explore nature.",
        "Everest Base Camp and Annapurna Circuit are top treks.",
        "Pokhara is the most beautiful place in Nepal.",
        "It is in the Kaski District, Nepal.",
        "Phewa Lake is a famous lake in Pokhara.",
        "Try paragliding, boating, and zip-lining.",
        "Ilam is famous for its tea gardens.",
        "Ilam is in eastern Nepal, Province 1.",
        "Chitwan is known for wildlife and safaris.",
        "Chitwan is in Bagmati Province, Nepal.",
        "A famous UNESCO site for wildlife lovers.",
        "Janakpur is the birthplace of Goddess Sita.",
        "Janakpur is in Madhesh Province, Nepal.",
        "A grand Hindu temple dedicated to Sita.",
        "Dharan is a vibrant city in eastern Nepal.",
        "Dharan is in Sunsari District, Nepal.",
        "Dhulikhel offers breathtaking Himalayan views.",
        "Dhulikhel is in the Kathmandu Valley.",
        "Kalinchowk is famous for snow and the Bhagwati Temple.",
        "It is in Dolakha District, Bagmati Province.",
        "Dolpa is a remote but beautiful trekking region.",
        "Dolpa is in Karnali Province, Nepal.",
        "Hello! How can I assist you?",
        "Hi there! Need any help?",
        "I'm doing great! How about you?",
        "Goodbye! Have a nice day.",
        "You're welcome!",
        "Happy to assist you!",
        "How can I help you today?",
        "Sure! What do you need support with?",
        "Would you like today's weather update?",
        "Why don’t programmers like nature? Too many bugs!",
        "Did you know? Mount Everest is the tallest mountain.",
        "Nepal is a beautiful country with rich culture.",
        "Momo, dal bhat, and sel roti are popular foods.",
        "Dashain and Tihar are major festivals.",
        "Nepal was never colonized by any country.",
        "Nepal is great for trekking, culture, and adventure.",
        "There are many budget and luxury hotels available.",
        "Tribhuvan International Airport is the main airport.",
        "Nepali Rupee (NPR) is the currency.",
        "Dial 100 for police and 102 for ambulance.",
        "Hospitals and clinics are available in major cities.",
        "ATMs are available in cities and towns.",
        "Banks like Nabil, NIC, and Everest Bank operate here.",
        "Thamel and New Road are great for shopping.",
        "Public buses are available but can be crowded.",
        "Nepal has limited railway services.",
        "Domestic flights connect major cities.",
        "Bikes can be rented in Kathmandu and Pokhara.",
        "Taxis are available but negotiate the fare.",
        "Thamel has many local and international restaurants.",
        "Visit Kathmandu, Pokhara, and Lumbini.",
        "The National Museum in Kathmandu is popular.",
        "Pashupatinath and Swayambhunath are famous temples.",
        "Kopan and Tengboche monasteries are well known.",
        "Gautama Buddha was born in Lumbini, Nepal.",
        "Hinduism is the major religion in Nepal.",
        "Nepal has great meditation centers like Vipassana.",
        "Kathmandu and Pokhara have many yoga retreats.",
        "Football and cricket are popular in Nepal.",
        "Nepal has an emerging cricket team.",
        "Nepal’s national football team competes internationally.",
        "IT is growing fast in Nepal.",
        "WiFi is available in most hotels and cafes.",
        "Try restarting your router or checking your plan.",
        "Reset your password via email or phone number.",
        "You can contact customer support for help.",
        "Google Maps can help you navigate Nepal.",
        "Autumn and spring are the best seasons.",
        "Backpacking is affordable with hostels and local food.",
        "Bhatbhateni and Civil Mall are popular.",
        "Nepali folk and pop music are widely loved.",
        "Kollywood is the Nepali film industry.",
        "Tihar is Nepal’s festival of lights.",
        "Nepal celebrates both Bikram Sambat and Gregorian New Year.",
        "Christmas is celebrated by the Christian community.",
        "Eid is celebrated by the Muslim community.",
        "Diwali is celebrated as Tihar in Nepal."
      ],
      backgroundColor: Colors.white,
      initialGreeting:
          "👋 Hello! \nWelcome to Gantabya\nHow can I assist you today?",
      defaultResponse: "Sorry, I didn't understand your response.",
      inactivityMessage: "Is there anything else you need help with?",
      closingMessage: "This conversation will now close.",
      inputHint: 'Send a message',
      waitingText: 'Please wait...',
    );
    return Container(
      decoration: const BoxDecoration(
          image: DecorationImage(
              image: AssetImage("assets/images/background.jpg"),
              fit: BoxFit.cover)),
      child: Scaffold(
        backgroundColor: Colors.transparent,
        appBar: AppBar(
          backgroundColor: Colors.transparent,
          title: const Text(
            'Gantabya chatbot',
            style: TextStyle(fontWeight: FontWeight.bold, color: Colors.white),
          ),
          centerTitle: true,
          iconTheme: const IconThemeData(color: Colors.white),
        ),
        body: ikchatbot(config: chatBotConfig),
      ),
    );
  }
}
